# Generated by Django 3.0 on 2019-12-20 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='users_id_example',
            field=models.CharField(default=[], max_length=10, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='items_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='users_num',
            field=models.CharField(max_length=10),
        ),
    ]
