# Generated by Django 3.0 on 2019-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0003_auto_20191220_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
