# Generated by Django 3.0 on 2020-01-22 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0004_auto_20191221_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='short',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='users_id_sample',
            field=models.CharField(max_length=100, validators=[django.core.validators.int_list_validator]),
        ),
    ]
