# Generated by Django 3.0 on 2020-01-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_auto_20191221_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='short',
            field=models.CharField(max_length=40),
        ),
    ]
