# Generated by Django 3.0 on 2020-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_auto_20200122_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
